#webapp/app.yaml
application: analyzetweets
version: 5
runtime: python27
api_version: 1
threadsafe: no
#threadsafe: false
handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.py
libraries:
- name: ssl
  version: latest
